@extends('layouts.app')
@section('title','Beranda')
@section('content')
<div class="page-head"><div><div class="eyebrow">{{ now('Asia/Jakarta')->translatedFormat('l, d F Y') }}</div><h1>Halo, {{ Str::before(auth()->user()->name,' ') }}.</h1><p>Jadwal dan tindakan penting Anda hari ini.</p></div><a class="button subtle" href="{{ route('leave') }}">+ Ajukan izin</a></div>
@if($pending)<div class="alert info">Ada {{ $pending }} pengajuan tim yang menunggu keputusan. <a href="{{ route('leave') }}">Tinjau sekarang</a></div>@endif
<div class="grid two"><section class="card"><div class="section-head"><h2>Shift terdekat</h2><span class="badge">{{ $shifts->count() }} jadwal</span></div>
@forelse($shifts as $shift)<article class="shift-item"><div class="shift-date"><b>{{ \Carbon\Carbon::parse($shift->start_at)->format('d') }}</b><span>{{ \Carbon\Carbon::parse($shift->start_at)->translatedFormat('M') }}</span></div><div class="shift-details"><strong>{{ \Carbon\Carbon::parse($shift->start_at)->format('H:i') }}–{{ \Carbon\Carbon::parse($shift->end_at)->format('H:i') }}</strong><small>{{ $shift->branch_name }} · {{ $shift->status==='approved'?'Disetujui':'Draf' }}</small>
@if($shift->attendance_status)<span class="badge {{ $shift->attendance_status==='absent'?'danger':'good' }}">{{ $shift->attendance_status==='absent'?'Alfa':($shift->checkout_at?'Selesai':'Sudah check-in') }}</span>@endif</div>
@if($shift->status==='approved' && !$shift->checkout_at && $shift->attendance_status!=='absent')<button class="button small" type="button" data-open-attendance="{{ $shift->id }}" data-action="{{ $shift->checkin_at?'out':'in' }}">{{ $shift->checkin_at?'Check-out':'Check-in' }}</button>@endif</article>
<div class="attendance-panel" id="attendance-{{ $shift->id }}" hidden><h3>Verifikasi {{ $shift->checkin_at?'check-out':'check-in' }}</h3><p>Pastikan Anda berada di cabang. Minta kode QR aktif di lokasi kerja; lokasi dikirim saat tombol ditekan.</p>
<form method="post" action="{{ route('attendance.act',$shift->id) }}" class="stack attendance-form">@csrf<input type="hidden" name="action" value="{{ $shift->checkin_at?'out':'in' }}"><input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="accuracy">
<label>Kode cabang 8 karakter<input name="qr_code" maxlength="8" minlength="8" autocapitalize="characters" placeholder="Contoh A1B2C3D4" required></label><label>Ketik angka {{ $challenge }}<input name="challenge" inputmode="numeric" maxlength="3" required></label>
<button class="button subtle small" type="button" data-scan-qr>Pindai QR</button><video class="qr-scanner" playsinline hidden></video><button class="button primary">Ambil lokasi & kirim</button><small class="form-status" aria-live="polite"></small></form>
<details><summary>Lokasi, kamera, atau jaringan bermasalah?</summary><form method="post" action="{{ route('attendance.exception',$shift->id) }}" class="stack">@csrf<input type="hidden" name="action" value="{{ $shift->checkin_at?'out':'in' }}"><label>Alasan pengecualian<textarea name="reason" minlength="10" required placeholder="Jelaskan kendala dan waktu kejadian"></textarea></label><button class="button subtle">Kirim ke manager</button></form></details></div>
@empty<p class="empty">Belum ada shift terjadwal. Hubungi admin jika jadwal seharusnya sudah tersedia.</p>@endforelse</section>
<section class="card"><div class="section-head"><h2>Status pengajuan</h2><a href="{{ route('leave') }}">Lihat semua →</a></div>
@forelse($leaves as $leave)<div class="list-row"><div><strong>{{ $leave->type==='sick'?'Sakit':'Izin' }}</strong><small>{{ $leave->start_date }} s.d. {{ $leave->end_date }}</small></div><span class="badge {{ $leave->status==='approved'?'good':($leave->status==='rejected'?'danger':'') }}">{{ ['pending'=>'Menunggu','approved'=>'Disetujui','partial'=>'Sebagian','rejected'=>'Ditolak'][$leave->status] ?? $leave->status }}</span></div>
@empty<p class="empty">Belum ada pengajuan.</p>@endforelse</section></div>
@endsection
