@extends('layouts.app')
@section('title','Payroll')
@section('content')
<div class="page-head"><div><div class="eyebrow">TAHAP 5</div><h1>Payroll</h1><p>Pratinjau rinci per karyawan. Persetujuan dan penguncian dilakukan terpisah.</p></div><span class="badge {{ $run && $run->status==='locked'?'good':'' }}">{{ $run ? strtoupper($run->status) : 'BELUM ADA DRAF' }}</span></div>
<section class="card"><form method="get" action="{{ route('payroll.index') }}" class="inline-form"><label>Cabang<select name="branch_id">@foreach($branches as $b)<option value="{{ $b->id }}" @selected($b->id==$branchId)>{{ $b->name }}</option>@endforeach</select></label><label>Bulan<input type="month" name="month" value="{{ $month }}" required></label><button class="button subtle">Lihat</button></form>
@if($blockers)<div class="alert info">Sebelum persetujuan, selesaikan: {{ implode(', ',$blockers) }}.</div>@endif
<div class="actions spaced">@if(!$run || $run->status==='draft')<form method="post" action="{{ route('payroll.generate') }}">@csrf<input type="hidden" name="branch_id" value="{{ $branchId }}"><input type="hidden" name="month" value="{{ $month }}"><button class="button primary">{{ $run?'Buat ulang draf':'Simpan draf' }}</button></form>@endif
@if($run && $run->status==='draft')<form method="post" action="{{ route('payroll.approve') }}">@csrf<input type="hidden" name="branch_id" value="{{ $branchId }}"><input type="hidden" name="month" value="{{ $month }}"><button class="button">Setujui periode</button></form>@endif
@if($run && $run->status==='approved')<form method="post" action="{{ route('payroll.lock') }}">@csrf<input type="hidden" name="branch_id" value="{{ $branchId }}"><input type="hidden" name="month" value="{{ $month }}"><button class="button">Kunci periode</button></form>@endif
@if($run && in_array($run->status,['approved','locked']))<a class="button subtle" href="{{ route('payroll.export',['branch_id'=>$branchId,'month'=>$month]) }}">Ekspor CSV</a>@endif</div></section>
@if(!$run || $run->status==='draft')<section class="card"><h2>Koreksi manual</h2><form method="post" action="{{ route('payroll.adjustment') }}" class="form-grid">@csrf<input type="hidden" name="month" value="{{ $month }}"><label>Karyawan<select name="user_id">@foreach($lines as $line)<option value="{{ $line['employee']->id }}">{{ $line['employee']->name }}</option>@endforeach</select></label><label>Jumlah (+ / − Rp)<input type="number" name="amount" required></label><label class="full">Alasan<input name="reason" required minlength="10"></label><button class="button small">Tambah koreksi</button></form></section>@endif
<section class="card"><div class="section-head"><h2>Rincian {{ $branch->name }} · {{ $month }}</h2><span class="badge">{{ count($lines) }} karyawan</span></div>
@forelse($lines as $line)@php($d=$line['detail'])<details class="payroll-person"><summary><span><strong>{{ $line['employee']->name }}</strong><small>Gaji bulanan Rp{{ number_format($d['monthly_salary'],0,',','.') }} · {{ $d['employed_days'] }}/{{ $d['calendar_days'] }} hari kerja kalender</small></span><b>Rp{{ number_format($d['net'],0,',','.') }}</b></summary>
<div class="payroll-breakdown"><div><span>Prorata gaji pokok</span><b>+ Rp{{ number_format($d['prorated_base'],0,',','.') }}</b></div><div><span>Hari tidak dibayar ({{ count($d['unpaid_dates']) }})</span><b>− Rp{{ number_format($d['unpaid_deduction'],0,',','.') }}</b></div>
<div><span>Potongan terlambat ({{ $d['late_units'] }} unit)</span><b>− Rp{{ number_format($d['late_deduction'],0,',','.') }}</b></div><div><span>Lembur disetujui ({{ $d['overtime_minutes'] }} menit)</span><b>+ Rp{{ number_format($d['overtime_pay'],0,',','.') }}</b></div><div><span>Koreksi manual</span><b>{{ $d['manual_total']>=0?'+':'−' }} Rp{{ number_format(abs($d['manual_total']),0,',','.') }}</b></div>
<p class="hint">Tarif harian Rp{{ number_format($d['daily_rate'],2,',','.') }}; tarif per jam Rp{{ number_format($d['hourly_rate'],2,',','.') }}. Sumber: tanggal tidak dibayar {{ implode(', ',$d['unpaid_dates']) ?: '—' }}; ID absensi terlambat {{ implode(', ',array_column($d['late_sources'],'attendance_id')) ?: '—' }}; ID absensi lembur {{ implode(', ',array_column($d['overtime_sources'],'attendance_id')) ?: '—' }}; ID koreksi {{ implode(', ',array_column($d['adjustments'],'id')) ?: '—' }}.</p></div></details>
@empty<p class="empty">Tidak ada karyawan untuk periode ini.</p>@endforelse</section>
@endsection
