@extends('layouts.app')
@section('title','Karyawan')
@section('content')
<div class="page-head"><div><div class="eyebrow">ADMINISTRASI</div><h1>Karyawan & cabang</h1><p>Kelola data kerja dan akses akun.</p></div><a class="button subtle" href="{{ route('import') }}">Impor Excel / CSV</a></div>
<div class="grid two"><section class="card"><h2>Tambah cabang</h2><form method="post" action="{{ route('branches.store') }}" class="form-grid">@csrf
<label>Kode cabang<input name="code" required placeholder="JKT01"></label><label>Nama cabang<input name="name" required></label>
<label>Lintang<input name="latitude" type="number" step="any" required placeholder="-6.200000"></label><label>Bujur<input name="longitude" type="number" step="any" required placeholder="106.816666"></label>
<label>Radius area (meter)<input name="radius_m" type="number" value="100" min="20" max="1000" required></label><button class="button primary align-end">Simpan cabang</button></form><p class="hint">Koordinat dan radius dipakai untuk validasi absensi. Periksa titik di lokasi cabang.</p></section>
<section class="card"><h2>Tambah akun</h2><form method="post" action="{{ route('people.store') }}" class="form-grid">@csrf
<label>Nama<input name="name" required></label><label>Email<input name="email" type="email" required></label>
<label>Sandi sementara<input name="password" type="password" minlength="10" required></label><label>Peran<select name="role"><option value="employee">Karyawan</option><option value="manager">Manager</option><option value="admin">Super admin</option></select></label>
<label>Cabang<select name="branch_id"><option value="">Pilih cabang</option>@foreach($branches as $b)<option value="{{ $b->id }}">{{ $b->name }}</option>@endforeach</select></label><label>Jabatan<select name="position_id"><option value="">Pilih jabatan</option>@foreach($positions as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label>
<label>Tanggal mulai<input name="hired_at" type="date" required></label><label>Tanggal akhir (opsional)<input name="ended_at" type="date"></label><label>Gaji bulanan (Rp)<input name="base_salary" type="number" min="0" required></label><button class="button primary">Buat akun</button></form></section></div>
<section class="card"><h2>Jabatan</h2><form method="post" action="{{ route('positions.store') }}" class="inline-form">@csrf<label>Nama jabatan<input name="name" required maxlength="100"></label><button class="button small">Tambah jabatan</button></form></section>
<section class="card"><h2>Lokasi cabang</h2><div class="grid two">@foreach($branches as $b)<details><summary>{{ $b->name }} · {{ $b->code }}</summary><form method="post" action="{{ route('branches.update',$b->id) }}" class="form-grid">@csrf<label>Nama<input name="name" value="{{ $b->name }}" required></label><label>Lintang<input type="number" step="any" name="latitude" value="{{ $b->latitude }}" required></label><label>Bujur<input type="number" step="any" name="longitude" value="{{ $b->longitude }}" required></label><label>Radius (m)<input type="number" name="radius_m" value="{{ $b->radius_m }}" min="20" max="1000" required></label><button class="button small">Simpan</button></form></details>@endforeach</div></section>
<section class="card"><div class="section-head"><h2>Daftar karyawan</h2><span class="badge">{{ $people->count() }} akun</span></div><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Cabang / jabatan</th><th>Peran</th><th>Gaji</th><th>Status</th><th>Kelola</th></tr></thead><tbody>@foreach($people as $p)<tr><td><strong>{{ $p->name }}</strong><small>{{ $p->email }}</small></td><td>{{ $p->branch_name ?? '—' }}<small>{{ $p->position_name ?? '—' }}</small></td><td>{{ $p->role }}</td><td>Rp{{ number_format($p->base_salary,0,',','.') }}</td><td><span class="badge {{ $p->active?'good':'danger' }}">{{ $p->active?'Aktif':'Nonaktif' }}</span></td><td><details><summary>Ubah</summary><form method="post" action="{{ route('people.update',$p->id) }}" class="stack compact">@csrf
<label>Nama<input name="name" value="{{ $p->name }}" required></label><label>Email<input type="email" name="email" value="{{ $p->email }}" required></label><label>Peran<select name="role">@foreach(['admin'=>'Super admin','manager'=>'Manager','employee'=>'Karyawan'] as $role=>$label)<option value="{{ $role }}" @selected($p->role===$role)>{{ $label }}</option>@endforeach</select></label>
<label>Cabang<select name="branch_id"><option value="">Tanpa cabang</option>@foreach($branches as $b)<option value="{{ $b->id }}" @selected($p->branch_id==$b->id)>{{ $b->name }}</option>@endforeach</select></label>
<label>Jabatan<select name="position_id"><option value="">Tanpa jabatan</option>@foreach($positions as $pos)<option value="{{ $pos->id }}" @selected($p->position_id==$pos->id)>{{ $pos->name }}</option>@endforeach</select></label>
<label>Mulai kerja<input type="date" name="hired_at" value="{{ $p->hired_at }}" required></label><label>Akhir kerja<input type="date" name="ended_at" value="{{ $p->ended_at }}"></label><label>Gaji bulanan<input type="number" name="base_salary" min="0" value="{{ $p->base_salary }}" required></label>
<label>Status<select name="active"><option value="1" @selected($p->active)>Aktif</option><option value="0" @selected(!$p->active)>Nonaktif</option></select></label><label>Sandi baru (opsional)<input name="password" type="password" minlength="10" autocomplete="new-password"></label>
<label class="check"><input type="checkbox" name="reset_device" value="1"> Reset perangkat absensi</label><button class="button primary small">Simpan</button></form></details></td></tr>@endforeach</tbody></table></div></section>
@endsection
