@extends('layouts.app')
@section('title','Aturan')
@section('content')
<div class="page-head"><div><div class="eyebrow">KEBIJAKAN</div><h1>Aturan perhitungan</h1><p>Perubahan berlaku pada perhitungan berikutnya. Periode yang dikunci tetap memakai snapshot lama.</p></div></div>
<section class="card"><form method="post" action="{{ route('settings.save') }}" class="form-grid">@csrf
<label>Pembagi tarif harian<select name="daily_divisor"><option value="calendar" @selected($settings['daily_divisor']==='calendar')>Jumlah hari kalender (disetujui)</option><option value="fixed_30" @selected($settings['daily_divisor']==='fixed_30')>Tetap 30 hari</option></select></label>
@foreach(['late_grace_minutes'=>'Toleransi terlambat (menit)','late_unit_minutes'=>'Kelipatan potongan (menit)','late_penalty_per_unit'=>'Potongan per unit (Rp)','late_reject_minutes'=>'Batas alfa / tolak check-in (menit)','checkin_early_minutes'=>'Check-in paling awal (menit)','checkout_late_hours'=>'Batas check-out setelah shift (jam)','overtime_threshold_minutes'=>'Ambang lembur (menit)','leave_notice_days'=>'Tenggat izin (hari sebelum mulai)','sick_paid_days_per_case'=>'Sakit dibayar per kejadian (hari)','hourly_divisor'=>'Pembagi tarif harian menjadi tarif per jam'] as $key=>$label)<label>{{ $label }}<input type="number" min="0" name="{{ $key }}" value="{{ $settings[$key] }}" required></label>@endforeach
<button class="button primary">Simpan aturan</button></form></section><section class="card"><h2>Rumus yang dipakai</h2><p>Tarif harian = gaji bulanan ÷ jumlah hari kalender bulan tersebut. Tarif per jam = tarif harian ÷ {{ $settings['hourly_divisor'] }}. Prorata = tarif harian × jumlah hari sejak mulai bekerja. Potongan alfa atau izin tidak dibayar = tarif harian × hari unik. Lembur disetujui = tarif per jam × menit setelah ambang ÷ 60.</p><p class="hint">Contoh: gaji Rp3.000.000 pada bulan 30 hari menghasilkan tarif harian Rp100.000 dan tarif per jam Rp{{ number_format(100000/$settings['hourly_divisor'],2,',','.') }}. Satu unit keterlambatan memotong Rp{{ number_format($settings['late_penalty_per_unit'],0,',','.') }}.</p></section>
@endsection
