@extends('layouts.app')
@section('title','Shift')
@section('content')
<div class="page-head"><div><div class="eyebrow">TAHAP 2</div><h1>Jadwal shift</h1><p>Shift baru berstatus draf. Perubahan jadwal yang telah disetujui kembali menjadi draf.</p></div></div>
@if(auth()->user()->role==='admin')<section class="card"><h2>Buat shift</h2><form method="post" action="{{ route('shifts.store') }}" class="form-grid">@csrf
<label>Karyawan<select name="user_id" required>@foreach($people as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label><label>Cabang<select name="branch_id" required>@foreach($branches as $b)<option value="{{ $b->id }}">{{ $b->name }}</option>@endforeach</select></label>
<label>Tanggal<input type="date" name="date" value="{{ now('Asia/Jakarta')->toDateString() }}" required></label><label>Mulai<input type="time" name="start_time" value="09:00" required></label><label>Selesai<input type="time" name="end_time" value="17:00" required></label><button class="button primary align-end">Buat draf</button></form><p class="hint">Jam selesai yang lebih awal dari jam mulai berarti shift melewati tengah malam.</p></section>@endif
<section class="card"><div class="section-head"><h2>Daftar shift</h2><span class="badge">{{ $shifts->count() }} shift</span></div><div class="table-wrap"><table><thead><tr><th>Karyawan</th><th>Cabang</th><th>Mulai / selesai</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>@forelse($shifts as $s)<tr><td><strong>{{ $s->employee_name }}</strong></td><td>{{ $s->branch_name }}</td><td>{{ $s->start_at }}<small>{{ $s->end_at }}</small></td><td><span class="badge {{ $s->status==='approved'?'good':'' }}">{{ $s->status==='approved'?'Disetujui':'Draf' }} · v{{ $s->version }}</span></td><td>@if(auth()->user()->role==='admin')<div class="actions">@if($s->status==='draft')<form method="post" action="{{ route('shifts.approve',$s->id) }}">@csrf<button class="button small">Setujui</button></form>@endif
<details><summary>Ubah</summary><form method="post" action="{{ route('shifts.update',$s->id) }}" class="stack compact">@csrf<label>Tanggal<input type="date" name="date" value="{{ substr($s->start_at,0,10) }}" required></label><label>Mulai<input type="time" name="start_time" value="{{ substr($s->start_at,11,5) }}" required></label><label>Selesai<input type="time" name="end_time" value="{{ substr($s->end_at,11,5) }}" required></label><label>Alasan<textarea name="reason" required minlength="5"></textarea></label><button class="button small">Simpan revisi</button></form></details></div>@endif</td></tr>@empty<tr><td colspan="5" class="empty">Belum ada shift.</td></tr>@endforelse</tbody></table></div></section>
@endsection
